// Auto-generated by Agicore — entity field state machine validators

export interface TransitionResult {
  allowed: boolean;
  failedConditions: string[];
}

// Business.stage state machine
export const businessStageTransitions = [
  {
    "from": "Idea",
    "to": "Validated",
    "match": "all",
    "conditions": [
      "StrategicPosition.value_proposition is present (not null)",
      "StrategicPosition.target_market is present (not null)",
      "SalesContact record count >= 1"
    ]
  },
  {
    "from": "Validated",
    "to": "Building",
    "match": "all",
    "conditions": [
      "SalesContact.notes is present (not null)"
    ]
  },
  {
    "from": "Building",
    "to": "Active",
    "match": "any",
    "conditions": [
      "FinancialSnapshot.revenue > 0",
      "SalesContact count >= 3 where stage = \"closed_won\""
    ]
  },
  {
    "from": "Active",
    "to": "Scaling",
    "match": "all",
    "conditions": [
      "FinancialSnapshot record count >= 2",
      "OperationsAudit.overall_score < 20"
    ]
  }
] as const;

export function canBusinessStageTransition(
  from: string,
  to: string,
  _checkCondition: (description: string) => boolean
): TransitionResult {
  const transition = businessStageTransitions.find(
    t => t.from === from && t.to === to
  );
  if (!transition) {
    return { allowed: false, failedConditions: [`No transition defined from "${from}" to "${to}"`] };
  }
  const failedConditions: string[] = [];
  const results = transition.conditions.map(c => {
    const passed = _checkCondition(c);
    if (!passed) failedConditions.push(c);
    return passed;
  });
  const allowed = transition.match === 'any'
    ? results.some(Boolean)
    : results.every(Boolean);
  return { allowed, failedConditions: allowed ? [] : failedConditions };
}
