// AI Service — Multi-provider chat with streaming
// Generated by Agicore — DO NOT EDIT BY HAND
// Re-run `agicore compile` to regenerate.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::path::PathBuf;
use std::sync::Mutex;
use tauri::{Emitter, Window};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatRequest {
    pub messages: Vec<Message>,
    pub model: String,
    #[serde(default)]
    pub system_prompt: Option<String>,
    #[serde(default)]
    pub max_tokens: Option<u32>,
    #[serde(default)]
    pub temperature: Option<f32>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Message {
    pub role: String,
    pub content: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatResponse {
    pub content: String,
    pub model: String,
    pub provider: String,
    pub input_tokens: u32,
    pub output_tokens: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StreamDelta {
    pub request_id: String,
    pub delta: String,
    pub done: bool,
}

pub type ApiKeyStore = Mutex<HashMap<String, String>>;

fn api_keys_path() -> PathBuf {
    let mut base = std::env::var("APPDATA")
        .ok()
        .map(PathBuf::from)
        .or_else(|| std::env::var("HOME").ok().map(|h| PathBuf::from(h).join(".config")))
        .unwrap_or_else(|| PathBuf::from("."));
    base = base.join("NovaSyn");
    base = base.join("api-keys.json");
    base
}

pub fn load_api_keys() -> HashMap<String, String> {
    let path = api_keys_path();
    if !path.exists() {
        return HashMap::new();
    }
    match std::fs::read_to_string(&path) {
        Ok(content) => serde_json::from_str(&content).unwrap_or_default(),
        Err(_) => HashMap::new(),
    }
}

pub fn save_api_keys(keys: &HashMap<String, String>) -> Result<(), String> {
    let path = api_keys_path();
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }
    let content = serde_json::to_string_pretty(keys).map_err(|e| e.to_string())?;
    std::fs::write(&path, content).map_err(|e| e.to_string())
}

#[tauri::command]
pub fn get_api_keys(store: tauri::State<'_, ApiKeyStore>) -> Result<HashMap<String, String>, String> {
    let keys = store.lock().map_err(|e| e.to_string())?;
    // Return masked keys to renderer (don't expose raw keys)
    let masked: HashMap<String, String> = keys.iter()
        .map(|(k, v)| {
            let masked = if v.len() > 8 {
                format!("{}...{}", &v[..4], &v[v.len()-4..])
            } else {
                "***".to_string()
            };
            (k.clone(), masked)
        })
        .collect();
    Ok(masked)
}

#[tauri::command]
pub fn set_api_key(provider: String, key: String, store: tauri::State<'_, ApiKeyStore>) -> Result<(), String> {
    let mut keys = store.lock().map_err(|e| e.to_string())?;
    if key.is_empty() {
        keys.remove(&provider);
    } else {
        keys.insert(provider, key);
    }
    save_api_keys(&keys)
}

fn provider_from_model(model: &str) -> &'static str {
    if model.starts_with("claude") { return "anthropic"; }
    if model.starts_with("gpt-") || model.starts_with("o1") || model.starts_with("o3") || model.starts_with("o4") || model.starts_with("chatgpt-") { return "openai"; }
    "anthropic"
}

#[tauri::command]
pub async fn send_chat(
    request: ChatRequest,
    request_id: String,
    window: Window,
    store: tauri::State<'_, ApiKeyStore>,
) -> Result<ChatResponse, String> {
    let provider = provider_from_model(&request.model);
    let api_key = {
        let keys = store.lock().map_err(|e| e.to_string())?;
        keys.get(provider).cloned()
    };
    let api_key = api_key.ok_or_else(|| format!("No API key configured for {}", provider))?;

    match provider {
        "anthropic" => call_anthropic(request, request_id, window, api_key).await,
        "openai" => call_openai(request, request_id, window, api_key).await,
        _ => Err(format!("Unsupported provider: {}", provider)),
    }
}

async fn call_anthropic(
    request: ChatRequest,
    request_id: String,
    window: Window,
    api_key: String,
) -> Result<ChatResponse, String> {
    let client = reqwest::Client::new();

    // Anthropic separates the system prompt from the message list
    let messages: Vec<serde_json::Value> = request.messages.iter()
        .filter(|m| m.role != "system")
        .map(|m| serde_json::json!({"role": m.role, "content": m.content}))
        .collect();

    let max_tokens = request.max_tokens.unwrap_or(8192);
    let mut body = serde_json::json!({
        "model": request.model,
        "max_tokens": max_tokens,
        "temperature": request.temperature.unwrap_or(0.7),
        "messages": messages,
        "stream": true,
    });
    if let Some(sys) = &request.system_prompt {
        body["system"] = serde_json::json!(sys);
    }

    let response = client
        .post("https://api.anthropic.com/v1/messages")
        .header("x-api-key", &api_key)
        .header("anthropic-version", "2023-06-01")
        .header("content-type", "application/json")
        .json(&body)
        .send()
        .await
        .map_err(|e| e.to_string())?;

    if !response.status().is_success() {
        let err_text = response.text().await.unwrap_or_default();
        return Err(format!("Anthropic API error: {}", err_text));
    }

    let mut full_content = String::new();
    let mut input_tokens = 0u32;
    let mut output_tokens = 0u32;
    let mut bytes_stream = response.bytes_stream();
    use futures_util::StreamExt;

    let stream_result: Result<(), String> = async {
        while let Some(chunk) = bytes_stream.next().await {
            let chunk = chunk.map_err(|e| e.to_string())?;
            let text = String::from_utf8_lossy(&chunk);
            for line in text.lines() {
                if let Some(data) = line.strip_prefix("data: ") {
                    if data == "[DONE]" { continue; }
                    if let Ok(event) = serde_json::from_str::<serde_json::Value>(data) {
                        let event_type = event["type"].as_str().unwrap_or("");
                        if event_type == "content_block_delta" {
                            if let Some(delta_text) = event["delta"]["text"].as_str() {
                                full_content.push_str(delta_text);
                                let _ = window.emit("chat-stream", StreamDelta {
                                    request_id: request_id.clone(),
                                    delta: delta_text.to_string(),
                                    done: false,
                                });
                            }
                        } else if event_type == "message_start" {
                            if let Some(t) = event["message"]["usage"]["input_tokens"].as_u64() {
                                input_tokens = t as u32;
                            }
                        } else if event_type == "message_delta" {
                            if let Some(t) = event["usage"]["output_tokens"].as_u64() {
                                output_tokens = t as u32;
                            }
                        }
                    }
                }
            }
        }
        Ok(())
    }.await;

    // Partial-content recovery: if the stream died but we got something,
    // return what we have rather than failing the whole request.
    if let Err(err) = stream_result {
        if full_content.is_empty() {
            return Err(format!("Anthropic stream failed: {}", err));
        }
        eprintln!("[Anthropic] stream interrupted after {} chars: {}", full_content.len(), err);
    }

    let _ = window.emit("chat-stream", StreamDelta {
        request_id: request_id.clone(),
        delta: String::new(),
        done: true,
    });

    Ok(ChatResponse {
        content: full_content,
        model: request.model,
        provider: "anthropic".to_string(),
        input_tokens,
        output_tokens,
    })
}

// True for OpenAI reasoning models (o1/o3/o4) — they require
// max_completion_tokens (not max_tokens) and don't accept temperature.
fn is_openai_reasoning_model(model: &str) -> bool {
    model.starts_with("o1") || model.starts_with("o3") || model.starts_with("o4")
}

// True for GPT-5.x — uses max_completion_tokens but still accepts temperature.
fn is_openai_gpt5(model: &str) -> bool {
    model.starts_with("gpt-5")
}

async fn call_openai(
    request: ChatRequest,
    request_id: String,
    window: Window,
    api_key: String,
) -> Result<ChatResponse, String> {
    let client = reqwest::Client::new();

    let mut messages: Vec<serde_json::Value> = vec![];
    if let Some(sys) = &request.system_prompt {
        messages.push(serde_json::json!({"role": "system", "content": sys}));
    }
    for m in &request.messages {
        messages.push(serde_json::json!({"role": m.role, "content": m.content}));
    }

    let max_tokens = request.max_tokens.unwrap_or(8192);
    let mut body = serde_json::json!({
        "model": request.model,
        "messages": messages,
        "stream": true,
        "stream_options": {"include_usage": true},
    });

    // Reasoning vs chat-completion parameter switch
    if is_openai_reasoning_model(&request.model) {
        // Reasoning models: max_completion_tokens, no temperature
        body["max_completion_tokens"] = serde_json::json!(max_tokens);
    } else if is_openai_gpt5(&request.model) {
        // GPT-5.x: max_completion_tokens, temperature ok
        body["max_completion_tokens"] = serde_json::json!(max_tokens);
        body["temperature"] = serde_json::json!(request.temperature.unwrap_or(0.7));
    } else {
        body["max_tokens"] = serde_json::json!(max_tokens);
        body["temperature"] = serde_json::json!(request.temperature.unwrap_or(0.7));
    }

    let response = client
        .post("https://api.openai.com/v1/chat/completions")
        .header("Authorization", format!("Bearer {}", api_key))
        .header("Content-Type", "application/json")
        .json(&body)
        .send()
        .await
        .map_err(|e| e.to_string())?;

    if !response.status().is_success() {
        let err_text = response.text().await.unwrap_or_default();
        return Err(format!("OpenAI API error: {}", err_text));
    }

    let mut full_content = String::new();
    let mut input_tokens = 0u32;
    let mut output_tokens = 0u32;
    let mut bytes_stream = response.bytes_stream();
    use futures_util::StreamExt;

    let stream_result: Result<(), String> = async {
        while let Some(chunk) = bytes_stream.next().await {
            let chunk = chunk.map_err(|e| e.to_string())?;
            let text = String::from_utf8_lossy(&chunk);
            for line in text.lines() {
                if let Some(data) = line.strip_prefix("data: ") {
                    if data == "[DONE]" { continue; }
                    if let Ok(event) = serde_json::from_str::<serde_json::Value>(data) {
                        if let Some(delta_text) = event["choices"][0]["delta"]["content"].as_str() {
                            full_content.push_str(delta_text);
                            let _ = window.emit("chat-stream", StreamDelta {
                                request_id: request_id.clone(),
                                delta: delta_text.to_string(),
                                done: false,
                            });
                        }
                        if let Some(usage) = event["usage"].as_object() {
                            input_tokens = usage.get("prompt_tokens").and_then(|v| v.as_u64()).unwrap_or(0) as u32;
                            output_tokens = usage.get("completion_tokens").and_then(|v| v.as_u64()).unwrap_or(0) as u32;
                        }
                    }
                }
            }
        }
        Ok(())
    }.await;

    if let Err(err) = stream_result {
        if full_content.is_empty() {
            return Err(format!("OpenAI stream failed: {}", err));
        }
        eprintln!("[OpenAI] stream interrupted after {} chars: {}", full_content.len(), err);
    }

    let _ = window.emit("chat-stream", StreamDelta {
        request_id: request_id.clone(),
        delta: String::new(),
        done: true,
    });

    Ok(ChatResponse {
        content: full_content,
        model: request.model,
        provider: "openai".to_string(),
        input_tokens,
        output_tokens,
    })
}

// ─── Model Discovery ─────────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ModelCapabilities {
    pub chat: bool,
    pub structured_output: bool,
    pub thinking: bool,
    pub vision: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ModelInfo {
    pub id: String,
    pub name: String,
    pub provider: String,
    pub model_id: String,
    pub context_window: u64,
    pub max_output_tokens: u64,
    pub capabilities: ModelCapabilities,
    pub created_at: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct ProviderCache {
    last_fetched: String,
    models: Vec<ModelInfo>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct ModelCacheFile {
    version: u32,
    providers: HashMap<String, ProviderCache>,
}

const CACHE_VERSION: u32 = 1;
const CACHE_TTL_SECS: i64 = 24 * 60 * 60;

fn model_cache_path() -> PathBuf {
    let mut p = api_keys_path();
    p.pop();
    p.join("model-cache.json")
}

fn load_model_cache() -> ModelCacheFile {
    match std::fs::read_to_string(model_cache_path()) {
        Ok(content) => {
            match serde_json::from_str::<ModelCacheFile>(&content) {
                Ok(c) if c.version == CACHE_VERSION => c,
                _ => ModelCacheFile { version: CACHE_VERSION, providers: HashMap::new() },
            }
        }
        Err(_) => ModelCacheFile { version: CACHE_VERSION, providers: HashMap::new() },
    }
}

fn save_model_cache(cache: &ModelCacheFile) {
    let path = model_cache_path();
    if let Some(parent) = path.parent() {
        let _ = std::fs::create_dir_all(parent);
    }
    if let Ok(content) = serde_json::to_string_pretty(cache) {
        let _ = std::fs::write(&path, content);
    }
}

fn cache_is_fresh(cache: &ModelCacheFile, provider: &str) -> bool {
    let entry = match cache.providers.get(provider) {
        Some(e) => e,
        None => return false,
    };
    match chrono::DateTime::parse_from_rfc3339(&entry.last_fetched) {
        Ok(dt) => {
            let age = chrono::Utc::now().signed_duration_since(dt.with_timezone(&chrono::Utc));
            age.num_seconds() < CACHE_TTL_SECS
        }
        Err(_) => false,
    }
}

// Detect dated model variants like "...-2024-08-06" without pulling in a regex crate
fn has_date_suffix(id: &str) -> bool {
    let bytes = id.as_bytes();
    if bytes.len() < 11 { return false; }
    for i in 0..=(bytes.len() - 11) {
        if bytes[i] == b'-'
            && bytes[i+1].is_ascii_digit() && bytes[i+2].is_ascii_digit()
            && bytes[i+3].is_ascii_digit() && bytes[i+4].is_ascii_digit()
            && bytes[i+5] == b'-'
            && bytes[i+6].is_ascii_digit() && bytes[i+7].is_ascii_digit()
            && bytes[i+8] == b'-'
            && bytes[i+9].is_ascii_digit() && bytes[i+10].is_ascii_digit()
        {
            return true;
        }
    }
    false
}

async fn discover_anthropic_models(api_key: &str) -> Result<Vec<ModelInfo>, String> {
    let client = reqwest::Client::new();
    let mut all = Vec::new();
    let mut after_id: Option<String> = None;

    loop {
        let mut url = "https://api.anthropic.com/v1/models?limit=100".to_string();
        if let Some(ref aid) = after_id {
            url.push_str(&format!("&after_id={}", aid));
        }
        let resp = client.get(&url)
            .header("x-api-key", api_key)
            .header("anthropic-version", "2023-06-01")
            .send()
            .await
            .map_err(|e| e.to_string())?;
        if !resp.status().is_success() {
            return Err(format!("Anthropic models {}: {}", resp.status(), resp.text().await.unwrap_or_default()));
        }
        let data: serde_json::Value = resp.json().await.map_err(|e| e.to_string())?;
        if let Some(arr) = data["data"].as_array() {
            for m in arr {
                let id = m["id"].as_str().unwrap_or("").to_string();
                if id.is_empty() { continue; }
                all.push(ModelInfo {
                    name: m["display_name"].as_str().unwrap_or(&id).to_string(),
                    id: id.clone(),
                    provider: "anthropic".to_string(),
                    model_id: id,
                    context_window: m["max_input_tokens"].as_u64().unwrap_or(200000),
                    max_output_tokens: m["max_tokens"].as_u64().unwrap_or(8192),
                    capabilities: ModelCapabilities {
                        chat: true,
                        structured_output: m["capabilities"]["structured_outputs"]["supported"].as_bool().unwrap_or(false),
                        thinking: m["capabilities"]["thinking"]["supported"].as_bool().unwrap_or(false),
                        vision: m["capabilities"]["image_input"]["supported"].as_bool().unwrap_or(false),
                    },
                    created_at: m["created_at"].as_str().unwrap_or("").to_string(),
                });
            }
        }
        if data["has_more"].as_bool().unwrap_or(false) {
            after_id = data["last_id"].as_str().map(|s| s.to_string());
            if after_id.is_none() { break; }
        } else {
            break;
        }
    }

    Ok(all)
}

async fn discover_openai_models(api_key: &str) -> Result<Vec<ModelInfo>, String> {
    let client = reqwest::Client::new();
    let resp = client.get("https://api.openai.com/v1/models")
        .header("Authorization", format!("Bearer {}", api_key))
        .send()
        .await
        .map_err(|e| e.to_string())?;
    if !resp.status().is_success() {
        return Err(format!("OpenAI models {}: {}", resp.status(), resp.text().await.unwrap_or_default()));
    }
    let data: serde_json::Value = resp.json().await.map_err(|e| e.to_string())?;
    let mut out = Vec::new();
    let chat_prefixes = ["gpt-", "o1", "o3", "o4", "chatgpt-"];
    let skip = ["realtime", "audio", "search", "transcribe", "tts", "whisper", "embedding", "dall-e", "gpt-image", "moderation"];
    if let Some(arr) = data["data"].as_array() {
        for m in arr {
            let id = m["id"].as_str().unwrap_or("").to_lowercase();
            if id.is_empty() { continue; }
            if !chat_prefixes.iter().any(|p| id.starts_with(p)) { continue; }
            if skip.iter().any(|p| id.contains(p)) { continue; }
            if id.starts_with("ft:") { continue; }
            // Skip dated versions (e.g., gpt-4o-2024-08-06): scan for "-YYYY-MM-DD"
            if has_date_suffix(&id) { continue; }
            let context = match id.as_str() {
                s if s.starts_with("gpt-5") => 400000,
                s if s.starts_with("gpt-4.1") => 1047576,
                s if s.starts_with("o3") || s.starts_with("o4") => 200000,
                s if s.starts_with("gpt-4o") || s.starts_with("chatgpt-4o") => 128000,
                _ => 128000,
            };
            let original_id = m["id"].as_str().unwrap_or("").to_string();
            let thinking = original_id.starts_with("o1") || original_id.starts_with("o3") || original_id.starts_with("o4");
            let vision = original_id.contains("4o") || original_id.starts_with("gpt-5") || original_id.contains("4.1");
            let created_at = m["created"].as_i64()
                .and_then(|s| chrono::DateTime::<chrono::Utc>::from_timestamp(s, 0))
                .map(|dt| dt.to_rfc3339())
                .unwrap_or_default();
            out.push(ModelInfo {
                id: original_id.clone(),
                name: original_id.clone(),
                provider: "openai".to_string(),
                model_id: original_id,
                context_window: context,
                max_output_tokens: 16384,
                capabilities: ModelCapabilities { chat: true, structured_output: true, thinking, vision },
                created_at,
            });
        }
    }
    Ok(out)
}

async fn discover_google_models(api_key: &str) -> Result<Vec<ModelInfo>, String> {
    let client = reqwest::Client::new();
    let mut out = Vec::new();
    let mut page_token: Option<String> = None;
    loop {
        let mut url = format!("https://generativelanguage.googleapis.com/v1beta/models?key={}&pageSize=100", api_key);
        if let Some(ref pt) = page_token {
            url.push_str(&format!("&pageToken={}", pt));
        }
        let resp = client.get(&url).send().await.map_err(|e| e.to_string())?;
        if !resp.status().is_success() {
            return Err(format!("Google models {}: {}", resp.status(), resp.text().await.unwrap_or_default()));
        }
        let data: serde_json::Value = resp.json().await.map_err(|e| e.to_string())?;
        if let Some(arr) = data["models"].as_array() {
            for m in arr {
                let raw_name = m["name"].as_str().unwrap_or("");
                let id = raw_name.strip_prefix("models/").unwrap_or(raw_name).to_string();
                if !id.starts_with("gemini-") { continue; }
                let supports_chat = m["supportedGenerationMethods"].as_array()
                    .map(|a| a.iter().any(|v| v.as_str() == Some("generateContent")))
                    .unwrap_or(false);
                if !supports_chat { continue; }
                out.push(ModelInfo {
                    id: id.clone(),
                    name: m["displayName"].as_str().unwrap_or(&id).to_string(),
                    provider: "google".to_string(),
                    model_id: id.clone(),
                    context_window: m["inputTokenLimit"].as_u64().unwrap_or(32000),
                    max_output_tokens: m["outputTokenLimit"].as_u64().unwrap_or(8192),
                    capabilities: ModelCapabilities {
                        chat: true,
                        structured_output: true,
                        thinking: id.contains("thinking"),
                        vision: true,
                    },
                    created_at: String::new(),
                });
            }
        }
        page_token = data["nextPageToken"].as_str().map(|s| s.to_string());
        if page_token.is_none() { break; }
    }
    Ok(out)
}

async fn discover_xai_models(api_key: &str) -> Result<Vec<ModelInfo>, String> {
    let client = reqwest::Client::new();
    let resp = client.get("https://api.x.ai/v1/models")
        .header("Authorization", format!("Bearer {}", api_key))
        .send()
        .await
        .map_err(|e| e.to_string())?;
    if !resp.status().is_success() {
        return Err(format!("xAI models {}: {}", resp.status(), resp.text().await.unwrap_or_default()));
    }
    let data: serde_json::Value = resp.json().await.map_err(|e| e.to_string())?;
    let mut out = Vec::new();
    if let Some(arr) = data["data"].as_array() {
        for m in arr {
            let id = m["id"].as_str().unwrap_or("").to_string();
            let lower = id.to_lowercase();
            if !lower.contains("grok") { continue; }
            if lower.contains("imagine") || lower.contains("image") || lower.contains("vision") { continue; }
            let created_at = m["created"].as_i64()
                .and_then(|s| chrono::DateTime::<chrono::Utc>::from_timestamp(s, 0))
                .map(|dt| dt.to_rfc3339())
                .unwrap_or_default();
            out.push(ModelInfo {
                id: id.clone(),
                name: id.clone(),
                provider: "xai".to_string(),
                model_id: id,
                context_window: 131072,
                max_output_tokens: 16384,
                capabilities: ModelCapabilities { chat: true, structured_output: true, thinking: false, vision: true },
                created_at,
            });
        }
    }
    Ok(out)
}

#[tauri::command]
pub async fn discover_models(
    force_refresh: bool,
    store: tauri::State<'_, ApiKeyStore>,
) -> Result<Vec<ModelInfo>, String> {
    let keys: HashMap<String, String> = {
        let g = store.lock().map_err(|e| e.to_string())?;
        g.clone()
    };

    let mut cache = load_model_cache();
    let mut all: Vec<ModelInfo> = Vec::new();
    let mut updated = false;

    for (provider, key_opt) in [
        ("anthropic", keys.get("anthropic")),
        ("openai",    keys.get("openai")),
        ("google",    keys.get("google")),
        ("xai",       keys.get("xai")),
    ] {
        let use_cache = !force_refresh && cache_is_fresh(&cache, provider);
        if use_cache {
            if let Some(entry) = cache.providers.get(provider) {
                all.extend(entry.models.clone());
                continue;
            }
        }
        let api_key = match key_opt {
            Some(k) if !k.is_empty() => k.clone(),
            _ => {
                if let Some(entry) = cache.providers.get(provider) {
                    all.extend(entry.models.clone());
                }
                continue;
            }
        };
        let result = match provider {
            "anthropic" => discover_anthropic_models(&api_key).await,
            "openai"    => discover_openai_models(&api_key).await,
            "google"    => discover_google_models(&api_key).await,
            "xai"       => discover_xai_models(&api_key).await,
            _ => Ok(Vec::new()),
        };
        match result {
            Ok(models) => {
                cache.providers.insert(provider.to_string(), ProviderCache {
                    last_fetched: chrono::Utc::now().to_rfc3339(),
                    models: models.clone(),
                });
                all.extend(models);
                updated = true;
            }
            Err(e) => {
                eprintln!("[ModelDiscovery] {} failed: {}", provider, e);
                if let Some(entry) = cache.providers.get(provider) {
                    all.extend(entry.models.clone());
                }
            }
        }
    }

    if updated {
        save_model_cache(&cache);
    }

    all.sort_by(|a, b| {
        a.provider.cmp(&b.provider).then(b.created_at.cmp(&a.created_at))
    });

    Ok(all)
}
